//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleActOfKindnessApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAKtehdytteot
    {
        public int TehdytTeotID { get; set; }
        public int KayttajaID { get; set; }
        public System.DateTime Tekopvm { get; set; }
        public int PalkintoID { get; set; }
        public System.DateTime VoimassaOloPvm { get; set; }
        public int TekoID { get; set; }
    }
}
